// AUTO-GENERATED from extras/bas2tap/bas2tap.c TokenMap
// Do not edit manually. Update via scripts if needed.
export interface TokenInfo {
  token: string | null;
  type: number;
  classes: number[];
}

export const TOKEN_MAP: TokenInfo[] = [
  { token: null, type: 6, classes: [0] },
  { token: null, type: 6, classes: [0] },
  { token: null, type: 6, classes: [0] },
  { token: null, type: 6, classes: [0] },
  { token: null, type: 6, classes: [0] },
  { token: null, type: 6, classes: [0] },
  { token: null, type: 6, classes: [0] },
  { token: null, type: 6, classes: [0] },
  { token: null, type: 6, classes: [0] },
  { token: null, type: 6, classes: [0] },
  { token: null, type: 6, classes: [0] },
  { token: null, type: 6, classes: [0] },
  { token: null, type: 6, classes: [0] },
  { token: "(eoln)", type: 6, classes: [0] },
  { token: null, type: 6, classes: [0] },
  { token: null, type: 6, classes: [0] },
  { token: null, type: 6, classes: [0] },
  { token: null, type: 6, classes: [0] },
  { token: null, type: 6, classes: [0] },
  { token: null, type: 6, classes: [0] },
  { token: null, type: 6, classes: [0] },
  { token: null, type: 6, classes: [0] },
  { token: null, type: 6, classes: [0] },
  { token: null, type: 6, classes: [0] },
  { token: null, type: 6, classes: [0] },
  { token: null, type: 6, classes: [0] },
  { token: null, type: 6, classes: [0] },
  { token: null, type: 6, classes: [0] },
  { token: null, type: 6, classes: [0] },
  { token: null, type: 6, classes: [0] },
  { token: null, type: 6, classes: [0] },
  { token: null, type: 6, classes: [0] },
  { token: " ", type: 6, classes: [0] },
  { token: "!", type: 6, classes: [0] },
  { token: "\"", type: 6, classes: [0] },
  { token: "#", type: 6, classes: [0] },
  { token: "$", type: 6, classes: [0] },
  { token: "%", type: 6, classes: [0] },
  { token: "&", type: 6, classes: [0] },
  { token: "'", type: 6, classes: [0] },
  { token: "(", type: 6, classes: [0] },
  { token: ")", type: 6, classes: [0] },
  { token: "*", type: 6, classes: [0] },
  { token: "+", type: 6, classes: [0] },
  { token: ",", type: 6, classes: [0] },
  { token: "-", type: 6, classes: [0] },
  { token: ".", type: 6, classes: [0] },
  { token: "/", type: 6, classes: [0] },
  { token: "0", type: 6, classes: [0] },
  { token: "1", type: 6, classes: [0] },
  { token: "2", type: 6, classes: [0] },
  { token: "3", type: 6, classes: [0] },
  { token: "4", type: 6, classes: [0] },
  { token: "5", type: 6, classes: [0] },
  { token: "6", type: 6, classes: [0] },
  { token: "7", type: 6, classes: [0] },
  { token: "8", type: 6, classes: [0] },
  { token: "9", type: 6, classes: [0] },
  { token: ":", type: 2, classes: [0] },
  { token: ";", type: 6, classes: [0] },
  { token: "<", type: 6, classes: [0] },
  { token: "=", type: 6, classes: [0] },
  { token: ">", type: 6, classes: [0] },
  { token: "?", type: 6, classes: [0] },
  { token: "@", type: 6, classes: [0] },
  { token: "A", type: 6, classes: [0] },
  { token: "B", type: 6, classes: [0] },
  { token: "C", type: 6, classes: [0] },
  { token: "D", type: 6, classes: [0] },
  { token: "E", type: 6, classes: [0] },
  { token: "F", type: 6, classes: [0] },
  { token: "G", type: 6, classes: [0] },
  { token: "H", type: 6, classes: [0] },
  { token: "I", type: 6, classes: [0] },
  { token: "J", type: 6, classes: [0] },
  { token: "K", type: 6, classes: [0] },
  { token: "L", type: 6, classes: [0] },
  { token: "M", type: 6, classes: [0] },
  { token: "N", type: 6, classes: [0] },
  { token: "O", type: 6, classes: [0] },
  { token: "P", type: 6, classes: [0] },
  { token: "Q", type: 6, classes: [0] },
  { token: "R", type: 6, classes: [0] },
  { token: "S", type: 6, classes: [0] },
  { token: "T", type: 6, classes: [0] },
  { token: "U", type: 6, classes: [0] },
  { token: "V", type: 6, classes: [0] },
  { token: "W", type: 6, classes: [0] },
  { token: "X", type: 6, classes: [0] },
  { token: "Y", type: 6, classes: [0] },
  { token: "Z", type: 6, classes: [0] },
  { token: "[", type: 6, classes: [0] },
  { token: "\\", type: 6, classes: [0] },
  { token: "]", type: 6, classes: [0] },
  { token: "^", type: 6, classes: [0] },
  { token: "_", type: 6, classes: [0] },
  { token: "`", type: 6, classes: [0] },
  { token: "a", type: 6, classes: [0] },
  { token: "b", type: 6, classes: [0] },
  { token: "c", type: 6, classes: [0] },
  { token: "d", type: 6, classes: [0] },
  { token: "e", type: 6, classes: [0] },
  { token: "f", type: 6, classes: [0] },
  { token: "g", type: 6, classes: [0] },
  { token: "h", type: 6, classes: [0] },
  { token: "i", type: 6, classes: [0] },
  { token: "j", type: 6, classes: [0] },
  { token: "k", type: 6, classes: [0] },
  { token: "l", type: 6, classes: [0] },
  { token: "m", type: 6, classes: [0] },
  { token: "n", type: 6, classes: [0] },
  { token: "o", type: 6, classes: [0] },
  { token: "p", type: 6, classes: [0] },
  { token: "q", type: 6, classes: [0] },
  { token: "r", type: 6, classes: [0] },
  { token: "s", type: 6, classes: [0] },
  { token: "t", type: 6, classes: [0] },
  { token: "u", type: 6, classes: [0] },
  { token: "v", type: 6, classes: [0] },
  { token: "w", type: 6, classes: [0] },
  { token: "x", type: 6, classes: [0] },
  { token: "y", type: 6, classes: [0] },
  { token: "z", type: 6, classes: [0] },
  { token: "{", type: 6, classes: [0] },
  { token: "|", type: 6, classes: [0] },
  { token: "}", type: 6, classes: [0] },
  { token: "~", type: 6, classes: [0] },
  { token: "", type: 6, classes: [0] },
  { token: "", type: 6, classes: [0] },
  { token: "", type: 6, classes: [0] },
  { token: "", type: 6, classes: [0] },
  { token: "", type: 6, classes: [0] },
  { token: "", type: 6, classes: [0] },
  { token: "", type: 6, classes: [0] },
  { token: "", type: 6, classes: [0] },
  { token: "", type: 6, classes: [0] },
  { token: "", type: 6, classes: [0] },
  { token: "", type: 6, classes: [0] },
  { token: "", type: 6, classes: [0] },
  { token: "", type: 6, classes: [0] },
  { token: "", type: 6, classes: [0] },
  { token: "", type: 6, classes: [0] },
  { token: "", type: 6, classes: [0] },
  { token: "", type: 6, classes: [0] },
  { token: "", type: 6, classes: [0] },
  { token: "", type: 6, classes: [0] },
  { token: "", type: 6, classes: [0] },
  { token: "", type: 6, classes: [0] },
  { token: "", type: 6, classes: [0] },
  { token: "", type: 6, classes: [0] },
  { token: "", type: 6, classes: [0] },
  { token: "", type: 6, classes: [0] },
  { token: "", type: 6, classes: [0] },
  { token: "", type: 6, classes: [0] },
  { token: "", type: 6, classes: [0] },
  { token: "", type: 6, classes: [0] },
  { token: "", type: 6, classes: [0] },
  { token: "", type: 6, classes: [0] },
  { token: "", type: 6, classes: [0] },
  { token: "", type: 6, classes: [0] },
  { token: " ", type: 6, classes: [0] },
  { token: "¡", type: 6, classes: [0] },
  { token: "¢", type: 6, classes: [0] },
  { token: "SPECTRUM", type: 1, classes: [0] },
  { token: "PLAY", type: 1, classes: [12] },
  { token: "RND", type: 3, classes: [0] },
  { token: "INKEY$", type: 4, classes: [0] },
  { token: "PI", type: 3, classes: [0] },
  { token: "FN", type: 3, classes: [1, 40, 13, 41, 0] },
  { token: "POINT", type: 3, classes: [40, 8, 41, 0] },
  { token: "SCREEN$", type: 4, classes: [40, 8, 41, 0] },
  { token: "ATTR", type: 3, classes: [40, 8, 41, 0] },
  { token: "AT", type: 5, classes: [8, 0] },
  { token: "TAB", type: 5, classes: [6, 0] },
  { token: "VAL$", type: 4, classes: [10, 0] },
  { token: "CODE", type: 3, classes: [10, 0] },
  { token: "VAL", type: 3, classes: [10, 0] },
  { token: "LEN", type: 3, classes: [10, 0] },
  { token: "SIN", type: 3, classes: [6, 0] },
  { token: "COS", type: 3, classes: [6, 0] },
  { token: "TAN", type: 3, classes: [6, 0] },
  { token: "ASN", type: 3, classes: [6, 0] },
  { token: "ACS", type: 3, classes: [6, 0] },
  { token: "ATN", type: 3, classes: [6, 0] },
  { token: "LN", type: 3, classes: [6, 0] },
  { token: "EXP", type: 3, classes: [6, 0] },
  { token: "INT", type: 3, classes: [6, 0] },
  { token: "SQR", type: 3, classes: [6, 0] },
  { token: "SGN", type: 3, classes: [6, 0] },
  { token: "ABS", type: 3, classes: [6, 0] },
  { token: "PEEK", type: 3, classes: [6, 0] },
  { token: "IN", type: 3, classes: [6, 0] },
  { token: "USR", type: 3, classes: [6, 0] },
  { token: "STR$", type: 4, classes: [6, 0] },
  { token: "CHR$", type: 4, classes: [6, 0] },
  { token: "NOT", type: 3, classes: [6, 0] },
  { token: "BIN", type: 6, classes: [0] },
  { token: "OR", type: 6, classes: [5, 0] },
  { token: "AND", type: 6, classes: [5, 0] },
  { token: "<=", type: 6, classes: [5, 0] },
  { token: ">=", type: 6, classes: [5, 0] },
  { token: "<>", type: 6, classes: [5, 0] },
  { token: "LINE", type: 6, classes: [0] },
  { token: "THEN", type: 6, classes: [0] },
  { token: "TO", type: 6, classes: [0] },
  { token: "STEP", type: 6, classes: [0] },
  { token: "DEF FN", type: 1, classes: [15, 0] },
  { token: "CAT", type: 1, classes: [11, 0] },
  { token: "FORMAT", type: 1, classes: [11, 0] },
  { token: "MOVE", type: 1, classes: [11, 0] },
  { token: "ERASE", type: 1, classes: [11, 0] },
  { token: "OPEN #", type: 1, classes: [11, 0] },
  { token: "CLOSE #", type: 1, classes: [11, 0] },
  { token: "MERGE", type: 1, classes: [11, 0] },
  { token: "VERIFY", type: 1, classes: [11, 0] },
  { token: "BEEP", type: 1, classes: [8, 0] },
  { token: "CIRCLE", type: 1, classes: [9, 44, 6, 0] },
  { token: "INK", type: 2, classes: [7, 0] },
  { token: "PAPER", type: 2, classes: [7, 0] },
  { token: "FLASH", type: 2, classes: [7, 0] },
  { token: "BRIGHT", type: 2, classes: [7, 0] },
  { token: "INVERSE", type: 2, classes: [7, 0] },
  { token: "OVER", type: 2, classes: [7, 0] },
  { token: "OUT", type: 1, classes: [8, 0] },
  { token: "LPRINT", type: 1, classes: [5, 0] },
  { token: "LLIST", type: 1, classes: [3, 0] },
  { token: "STOP", type: 1, classes: [0] },
  { token: "READ", type: 1, classes: [14, 0] },
  { token: "DATA", type: 2, classes: [13, 0] },
  { token: "RESTORE", type: 1, classes: [3, 0] },
  { token: "NEW", type: 1, classes: [0] },
  { token: "BORDER", type: 1, classes: [6, 0] },
  { token: "CONTINUE", type: 1, classes: [0] },
  { token: "DIM", type: 1, classes: [1, 40, 13, 41, 0] },
  { token: "REM", type: 1, classes: [5, 0] },
  { token: "FOR", type: 1, classes: [4, 61, 6, 204, 6, 205, 6, 0] },
  { token: "GO TO", type: 1, classes: [6, 0] },
  { token: "GO SUB", type: 1, classes: [6, 0] },
  { token: "INPUT", type: 1, classes: [5, 0] },
  { token: "LOAD", type: 1, classes: [11, 0] },
  { token: "LIST", type: 1, classes: [3, 0] },
  { token: "LET", type: 1, classes: [1, 61, 2, 0] },
  { token: "PAUSE", type: 1, classes: [6, 0] },
  { token: "NEXT", type: 1, classes: [4, 0] },
  { token: "POKE", type: 1, classes: [8, 0] },
  { token: "PRINT", type: 1, classes: [5, 0] },
  { token: "PLOT", type: 1, classes: [9, 0] },
  { token: "RUN", type: 1, classes: [3, 0] },
  { token: "SAVE", type: 1, classes: [11, 0] },
  { token: "RANDOMIZE", type: 1, classes: [3, 0] },
  { token: "IF", type: 1, classes: [6, 203, 0] },
  { token: "CLS", type: 1, classes: [0] },
  { token: "DRAW", type: 1, classes: [9, 44, 6, 0] },
  { token: "CLEAR", type: 1, classes: [3, 0] },
  { token: "RETURN", type: 1, classes: [0] },
  { token: "COPY", type: 1, classes: [0] },
];